package be.ehb.security;

/**
 * @author Guillaume Vandecasteele
 * @since 2017
 */
public enum PermissionType {

    ORG_VIEW, ORG_EDIT, ORG_ADMIN,
    PROJECT_VIEW, PROJECT_VIEW_ALL, PROJECT_EDIT, PROJECT_ADMIN,
    ACTIVITY_VIEW, ACTIVITY_EDIT, ACTIVITY_ADMIN,
    WORKLOG_VIEW, WORKLOG_VIEW_ALL, WORKLOG_EDIT, WORKLOG_EDIT_ALL, WORKLOG_ADMIN, WORKLOG_ADMIN_ALL

}
